GET http://localhost:8383/cart
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE2MDgyMzNhMTZiMTFlODJkN2IyYmYiLCJjYXJ0IjpbeyJfaWQiOiI2MjFjOTQxMjg1MWVjZjU1NzE5NGQ1YmIiLCJ0aXRsZSI6InRzaGlydDEyIiwiY2F0ZWdvcnkiOiJjbG90aGVzIiwiZGVzY3JpcHRpb24iOiJibGFjayIsImltZyI6Impoa2hraCIsInByaWNlIjoxMiwiY3JlYXRlZF9ieSI6IjYyMTYyZDQxMTQ3OGVmMzEzNzQxZjFhYyIsIl9fdiI6MCwicXR5IjoxNX0seyJfaWQiOiI2MjFjYmMyOTY2MThhMjZjMWFhYTZiYzkiLCJ0aXRsZSI6InRzaGlydG5lZWIiLCJjYXRlZ29yeSI6ImNsb3RoZXMiLCJkZXNjcmlwdGlvbiI6ImJsYWNrIiwiaW1nIjoiamhraGtoIiwicHJpY2UiOjEyLCJjcmVhdGVkX2J5IjoiNjIxNjA4MjMzYTE2YjExZTgyZDdiMmJmIiwiX192IjowLCJxdHkiOjN9XSwiaWF0IjoxNjQ2MDUyNDE3LCJleHAiOjE2NDYxMzg4MTd9.w4uoao38F69lLnNSPasyvoVbPTXHbfeyjUGnxuKPUW8

###
DELETE http://localhost:8383/cart
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE2MDgyMzNhMTZiMTFlODJkN2IyYmYiLCJjYXJ0IjpbeyJfaWQiOiI2MjFjOTQxMjg1MWVjZjU1NzE5NGQ1YmIiLCJ0aXRsZSI6InRzaGlydDEyIiwiY2F0ZWdvcnkiOiJjbG90aGVzIiwiZGVzY3JpcHRpb24iOiJibGFjayIsImltZyI6Impoa2hraCIsInByaWNlIjoxMiwiY3JlYXRlZF9ieSI6IjYyMTYyZDQxMTQ3OGVmMzEzNzQxZjFhYyIsIl9fdiI6MCwicXR5IjoxNX0seyJfaWQiOiI2MjFjYmMyOTY2MThhMjZjMWFhYTZiYzkiLCJ0aXRsZSI6InRzaGlydG5lZWIiLCJjYXRlZ29yeSI6ImNsb3RoZXMiLCJkZXNjcmlwdGlvbiI6ImJsYWNrIiwiaW1nIjoiamhraGtoIiwicHJpY2UiOjEyLCJjcmVhdGVkX2J5IjoiNjIxNjA4MjMzYTE2YjExZTgyZDdiMmJmIiwiX192IjowLCJxdHkiOjZ9XSwiaWF0IjoxNjQ2MDUyNTIwLCJleHAiOjE2NDYxMzg5MjB9.R4grmFvru3lNPWxySnDaFDrymUe8LDEH6G6b4SpkEFk
###
PUT http://localhost:8383/cart/621c9412851ecf557194d5bb
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE2MDgyMzNhMTZiMTFlODJkN2IyYmYiLCJjYXJ0IjpbeyJfaWQiOiI2MjFjOTQxMjg1MWVjZjU1NzE5NGQ1YmIiLCJ0aXRsZSI6InRzaGlydDEyIiwiY2F0ZWdvcnkiOiJjbG90aGVzIiwiZGVzY3JpcHRpb24iOiJibGFjayIsImltZyI6Impoa2hraCIsInByaWNlIjoxMiwiY3JlYXRlZF9ieSI6IjYyMTYyZDQxMTQ3OGVmMzEzNzQxZjFhYyIsIl9fdiI6MCwicXR5IjoxNX0seyJfaWQiOiI2MjFjYmMyOTY2MThhMjZjMWFhYTZiYzkiLCJ0aXRsZSI6InRzaGlydG5lZWIiLCJjYXRlZ29yeSI6ImNsb3RoZXMiLCJkZXNjcmlwdGlvbiI6ImJsYWNrIiwiaW1nIjoiamhraGtoIiwicHJpY2UiOjEyLCJjcmVhdGVkX2J5IjoiNjIxNjA4MjMzYTE2YjExZTgyZDdiMmJmIiwiX192IjowLCJxdHkiOjZ9XSwiaWF0IjoxNjQ2MDUyNTIwLCJleHAiOjE2NDYxMzg5MjB9.R4grmFvru3lNPWxySnDaFDrymUe8LDEH6G6b4SpkEFk

{
   "qty":"20"
}


###
POST http://localhost:8383/cart/621cbc296618a26c1aaa6bc9
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE2MDgyMzNhMTZiMTFlODJkN2IyYmYiLCJjYXJ0IjpbeyJfaWQiOiI2MjFjOTQxMjg1MWVjZjU1NzE5NGQ1YmIiLCJ0aXRsZSI6InRzaGlydDEyIiwiY2F0ZWdvcnkiOiJjbG90aGVzIiwiZGVzY3JpcHRpb24iOiJibGFjayIsImltZyI6Impoa2hraCIsInByaWNlIjoxMiwiY3JlYXRlZF9ieSI6IjYyMTYyZDQxMTQ3OGVmMzEzNzQxZjFhYyIsIl9fdiI6MCwicXR5IjoxNX0seyJfaWQiOiI2MjFjYmMyOTY2MThhMjZjMWFhYTZiYzkiLCJ0aXRsZSI6InRzaGlydG5lZWIiLCJjYXRlZ29yeSI6ImNsb3RoZXMiLCJkZXNjcmlwdGlvbiI6ImJsYWNrIiwiaW1nIjoiamhraGtoIiwicHJpY2UiOjEyLCJjcmVhdGVkX2J5IjoiNjIxNjA4MjMzYTE2YjExZTgyZDdiMmJmIiwiX192IjowLCJxdHkiOjN9XSwiaWF0IjoxNjQ2MDUyNDE3LCJleHAiOjE2NDYxMzg4MTd9.w4uoao38F69lLnNSPasyvoVbPTXHbfeyjUGnxuKPUW8

{
    "qty":3
}
