GET http://localhost:8383/products 

###
GET http://localhost:8383/products


###
POST http://localhost:8383/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTYxM2RhM2ExNmIxMWU4MmQ3YjJjMSIsImlhdCI6MTY0NTc3NDQwMSwiZXhwIjoxNjQ1ODYwODAxfQ.GQmBZKkwHt2Lu_kcKkvBkRpsBG2MmpbMVBTn6KcQwqk

{
        "title":"bmw",
        "category": "car",
        "description":"black",
        "img": "jhkhkhdcxs",
        "price": 1200.00
}

###
DELETE http://localhost:8383/products

###
PATCH http://localhost:8383/products
Content-Type: application/json

{
    "name":"new product"
}