GET http://localhost:9000/users 

###
GET http://localhost:9000/users


###
POST http://localhost:9000/users/signup
Content-Type: application/json

{
        "fullname":"aashcxsdsad",
        "password":"Allisjhcg7es",
        "email": "asdajashxgsd@gmail.com",
        "phone_number": "0684305634"

}


###
DELETE http://localhost:9000/users/6218bc42f12ac86552779f89

###
PATCH http://localhost:9000/users/6216158b05dbf743a55f8355
Content-Type: application/json

{
    "name":"master encrypto"
}