GET http://localhost:9000/users 

###
GET http://localhost:9000/users


###
POST http://localhost:9000/users/signup
Content-Type: application/json

{
        "fullname":"Diego",
        "password":"Allies",
        "email": "diegoallies27@gmail.com",
        "phone_number": "0684005634"
}


###
DELETE http://localhost:9000/users/62161dc06dcd92ecd4d2bfea

###
PATCH http://localhost:9000/users/6216158b05dbf743a55f8355
Content-Type: application/json

{
    "name":"master encrypto"
}